MyApp/MyApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', RedirectView.as_view(url='home')),
    path("__reload__/", include("django_browser_reload.urls")),
]

MyApp/app/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'app'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('profil/', ProfileView.as_view(), name='profil'),
    path('user_infos/', UserInfosView.as_view(), name='user_infos'),
    path('update_infos/', UserInfosUpdateView.as_view(), name='update_infos'),
    path('create_insurance_infos/', InsuranceInfosCreateView.as_view(), name='create_insurance_infos'),
    path('logout', LogoutView.as_view(), name='logout'),
    #path('prediction', get_prediction_page, name='prediction'),
    path('prediction/', PredictionTemplateView.as_view(), name='prediction'),
    #path('prediction/', PredictionView.as_view(), name='prediction'),
]

MyApp/app/templates/includes/navbar_section.html
{% load static %}

<!-- Navbar Section -->
{% block navbar %}
    <nav class="bg-navy-600 text-white p-4 shadow-md">
        <div class="container mx-auto flex justify-between items-center">
            <div class="space-x-6 flex items-center">
                <form action="{% url 'app:logout' %}" method="post">
                    {% csrf_token %}
                    <button type='submit'class="hover:text-[#00bfae] transition duration-300">Déconnexion</button>
                </form>
                <a href="{% url 'app:profil' %}" class="hover:text-[#00bfae] transition duration-300">Profil</a>
                <a href="{% url 'app:user_infos' %}" class="hover:text-[#00bfae] transition duration-300">Mes informations</a>
                <a href="{% url 'app:prediction' %}" class="hover:text-[#00bfae] transition duration-300">Estimation</a>
            </div>
        </div>
    </nav>
{% endblock %}

MyApp/app/templates/includes/prediction_simplest.html
<div style="border:solid; margin: right; width: 95%">
    <table><tr>
        <td>age : {{ insurance_infos.age }} ans </td>
        <td>sex : {{ insurance_infos.sex }} </td>
        <td>bmi : {{ insurance_infos.bmi }} </td>
        <td>children {{ insurance_infos.children }} enfants </td>
        <td>smoker : {{ insurance_infos.smoker }} </td>
        <td>region : {{ insurance_infos.region }} </td>
    </tr></table>
    
    <p class ="box"> Prédiction : <strong> {{ prediction }} $</strong></p>
    

    <div style="text-align: center;" >
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="cta-button" style="width: 300px; height:50px;">Enregistrer</button>
        </form>
    </div>

</div>

MyApp/app/templates/includes/prediction_with_template.html
{% block content %}

<div style="text-align: center;" >
    <form method="post">
        {% csrf_token %}
        {{ info_form.as_p }}
        <p> Indice de masse corporelle (IMC) : {{ bmi }}
        <p class ="box"> Prédiction ($): <strong> {{ prediction }} </strong></p>
        <button type="submit" class="cta-button" style="width: 300px; height:50px;">Mettre à jour et enregistrer</button>
    </form>
</div>

{% endblock %}